image: devkinetic/bitbucket-pipelines-agent:dev

pipelines:
  # Build sandboxes for all branches
  default:
    - step:
        script:
          # Initialize the agent configuration
          - source build-env
          # Initialize the remote sandbox environment
          - build-init
          - slack "Started sandbox build for branch *${BITBUCKET_BRANCH}*"
          # Run fin init on the remote docker host to provision a sandbox
          - ssh docker-host "cd $REMOTE_BUILD_DIR && fin init"
          - slack "Completed sandbox build for branch *${BITBUCKET_BRANCH}*:\n<http://${DOMAIN}|http://${DOMAIN}>"
